# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Unit tests
on:
  pull_request:
  workflow_call:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests (${{ matrix.os }}, Python ${{ matrix.python_version }}, Arch ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python_version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        architecture:
          - "x86"
          - "x64"
          - "arm64"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "${{matrix.python_version}}"
          architecture: "${{matrix.architecture}}"

      - run: |
          python -c 'import platform; print(f"{platform.system()}-{platform.machine()}");'

